wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1657889362
    t:
      1:
      - 1
      - 52
      - 55
      3:
      - 16
      4: 3.7.11
      5: 0.12.21
      8:
      - 5
lr:
  desc: null
  value: 0.00035922052403744136
