wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1657884542
    t:
      1:
      - 1
      - 52
      - 55
      3:
      - 16
      4: 3.7.11
      5: 0.12.18
      8:
      - 5
hypernet_embed:
  desc: null
  value: 64
hypernet_layers:
  desc: null
  value: 2
mixing_embed_dim:
  desc: null
  value: 32
