wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1657883772
    t:
      1:
      - 1
      - 52
      - 55
      2:
      - 1
      - 52
      - 55
      3:
      - 16
      - 24
      4: 3.7.11
      5: 0.12.18
      8:
      - 5
epsilon_finish:
  desc: null
  value: 0.08688599157893058
hypernet_embed:
  desc: null
  value: 38
hypernet_layers:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.0009614298055517252
mixing_embed_dim:
  desc: null
  value: 58
