wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1657643725
    t:
      1:
      - 1
      - 52
      - 55
      3:
      - 16
      4: 3.7.11
      5: 0.12.18
      8:
      - 5
entropy_coef:
  desc: null
  value: 0.09282289873403976
eps_clip:
  desc: null
  value: 0.31991376569251284
lr:
  desc: null
  value: 0.00022391400569222243
